apiVersion: apps/v1
kind: Deployment
metadata:
  name: personicle-schema-validation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personicle-schema-validation
  template:
    metadata:
      labels:
        app: personicle-schema-validation
    spec:
      containers:
      - name: personicle-schema-validation
        image: personicleservices.azurecr.io/personicle-schema-validation
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: INGESTION_PROD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: INGESTION_PROD
        - name: DATA_DICTIONARY_PORT
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DATA_DICTIONARY_PORT
        - name: DATA_DICTIONARY_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DATA_DICTIONARY_HOST
        
---
apiVersion: v1
kind: Service
metadata:
  name: personicle-schema-validation-service
spec:
  ports:
  - port: 5001
    name: http2
    protocol: TCP
    targetPort: 5001
  selector:
    app: personicle-schema-validation-service
