apiVersion: apps/v1
kind: Deployment
metadata:
  name: personicle-schema-validation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personicle-schema-validation
  template:
    metadata:
      labels:
        app: personicle-schema-validation
    spec:
      containers:
      - name: personicle-schema-validation
        image: personicleauth.azurecr.io/personicle-schema-validation
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: PASSWORD
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: HOST
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: NAME
        - name: AUTH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: AUTH_ENDPOINT
        - name: INGESTION_PROD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: INGESTION_PROD
        - name: DATA_DICTIONARY_PORT
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DATA_DICTIONARY_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: personicle-schema-validation
spec:
  ports:
  - port: 5002
    name: schema-validation
    protocol: TCP
    targetPort: 5002
  selector:
    app: personicle-schema-validation
