apiVersion: v1
kind: Service
metadata:
    name: "personiclecluster-9e4d"
    labels:
        app: "personiclecluster-9e4d"
spec:
    type: LoadBalancer
    ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: http
    selector:
        app: "personiclecluster-9e4d"